services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_blog_container
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-db
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_SECURE_COOKIE=false # For local development
      - WEBHOOK_URL=https://${NGROK_DOMAIN}
      - N8N_EDITOR_BASE_URL=https://${NGROK_DOMAIN}
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - ../n8n_data:/home/node/.n8n
    depends_on:
      - n8n-db
      - ngrok
    networks:
      - n8n-network

  n8n-db:
    image: postgres:14
    container_name: n8n_db_local
    restart: unless-stopped
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8npass
      - POSTGRES_DB=n8n
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - n8n-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_local
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
      - NGROK_DOMAIN=${NGROK_DOMAIN}
    command: ["http", "n8n:5678", "--domain=${NGROK_DOMAIN}"] # Replace with your domain if needed
    networks:
      - n8n-network

volumes:
  n8n_data:
  postgres_data:

networks:
  n8n-network:
    driver: bridge